### ISSUE TITLE
C Syntax Highlighting Not Quite Complete

### ISSUE THREAD

**Issue by benbenolson** [kammerdienerb/yed#4]
The C syntax highlighting might benefit from searching for `#if 0` and highlighting everything inside it as a comment. It's an edge case, but some people use that for comments.

**Comment by kammerdienerb** [comment]
This needs to be done in `syntax_c_frame_handler()` for `EVENT_FRAME_PRE_BUFF_DRAW`. That is the function that is responsible for marking lines as "in a comment", which are then highlighted by `syntax_c_line_handler()` for `EVENT_LINE_PRE_DRAW`. We need to mostly just check for `#if 0` and `#endif` delimiters, but it's more complicated than the `/* ... */` case because `#if` can be nested. So the solution probably needs to do some balance checking akin to matching parentheses.
